name: Build & Deploy Staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Staging Upfront-V4
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's SSH private key in PEM format

          script: |
            cd /home/react-staging/upfront2
            echo sudo -S git config --global --add safe.directory /home/react-staging/upfront2
            echo sudo -S git pull origin main
            echo sudo -S sudo npm install
            echo sudo -S sudo npm run build
            sudo -S pm2 restart 23
